[package]
name = "diesel_mysql"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]
edition = "2021"

[dependencies]
diesel = { version = "2.2", features = ["mysql"] }
dotenv = "0.15"
